### ISSUE TITLE
Run this project in eclipse ,show below error.

### ISSUE THREAD

**Issue by Zeping-Jian** [IceCubeDev/LiteCube_Android#1]
10-15 19:22:37.131: E/Mesh(5511): Loading texture: crate.bmp.001
10-15 19:22:37.131: W/System.err(5511): java.io.FileNotFoundException: crate.bmp.001
10-15 19:22:37.139: W/System.err(5511):     at android.content.res.AssetManager.openAsset(Native Method)
10-15 19:22:37.146: W/System.err(5511):     at android.content.res.AssetManager.open(AssetManager.java:338)
10-15 19:22:37.146: W/System.err(5511):     at android.content.res.AssetManager.open(AssetManager.java:312)
10-15 19:22:37.146: W/System.err(5511):     at com.supernovamobile.smashout.SMModel.loadTextures(SMModel.java:55)
10-15 19:22:37.146: W/System.err(5511):     at com.supernovamobile.smashout.SMGroup.loadTextures(SMGroup.java:71)
10-15 19:22:37.146: W/System.err(5511):     at com.supernovamobile.smashout.SmashoutGLRenderer.onSurfaceCreated(SmashoutGLRenderer.java:135)
10-15 19:22:37.146: W/System.err(5511):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
10-15 19:22:37.146: W/System.err(5511):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)
10-15 19:22:37.178: A/libc(5511): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 5527 (Thread-2331)

**Comment by IceCubeDev** [comment]
You are missing the file crate.bmp. This does not seem to be part of the LiteCube framework?
